### ISSUE TITLE
ReferenceError: StateMachine is not defined (on server)

### ISSUE THREAD

**Issue by pawelos88** [nate-strauser/meteor-statemachine#2]
Hi,
when trying to use StateMachine on server (i.e. in a Meteor shell), I get "ReferenceError: StateMachine is not defined". It works well on a client.
Do you know what might be the reason?
Thanks.

**Comment by nate-strauser** [comment]
i've never tried it from the shell, but it does work for me on client and
server code.  Can you provide the console output showing the commands used?

**Comment by gerwinbrunner** [comment]
I have the same issue.
It seems that it is a loading order issue / timing issue on the server.

```
I20150907-10:41:19.833(2)? typeof exports undefined false
I20150907-10:41:19.834(2)? typeof module undefined false
I20150907-10:41:19.834(2)? typeof define undefined false
I20150907-10:41:19.834(2)? typeof window undefined false
I20150907-10:41:19.834(2)? typeof self undefined false
```

I added these log statements to the state-machine.js file just before the check code.
https://github.com/jakesgordon/javascript-state-machine/blob/b5e3918837f4c6902ffa33346fcb6ec2e40962e2/state-machine.js#L198

```
  console.log("typeof exports", typeof exports, typeof exports !== 'undefined');
  console.log("typeof module", typeof module, typeof module !== 'undefined' && module.exports);
  console.log("typeof define", typeof define, typeof define === 'function' && define.amd);
  console.log("typeof window", typeof window, typeof window !== 'undefined');
  console.log("typeof self", typeof self, typeof self !== 'undefined');
```

This means that on the server the Statemachine is not initialized because it thinks that it is not a node server... Any idea on how to force the loading to be done at a later point?

**Comment by gerwinbrunner** [comment]
When a restart happens then the module loads correctly sometimes...

```
I20150907-11:12:18.876(2)? typeof exports undefined false
I20150907-11:12:18.877(2)? typeof module object { Object: {},
I20150907-11:12:18.877(2)?   Function: {},
I20150907-11:12:18.877(2)?   Array: {},
I20150907-11:12:18.877(2)?   String: {},
I20150907-11:12:18.877(2)?   Date: {},
I20150907-11:12:18.877(2)?   Number: {},
I20150907-11:12:18.877(2)?   Math: {},
I20150907-11:12:18.877(2)?   RegExp: {},
I20150907-11:12:18.877(2)?   wrap: [Function: wrap],
I20150907-11:12:18.877(2)?   isGeneratorFunction: [Function],
I20150907-11:12:18.877(2)?   mark: [Function],
I20150907-11:12:18.878(2)?   awrap: [Function],
I20150907-11:12:18.878(2)?   async: [Function],
I20150907-11:12:18.878(2)?   keys: [Function],
I20150907-11:12:18.878(2)?   values: [Function: values] }
I20150907-11:12:18.878(2)? typeof define undefined false
I20150907-11:12:18.878(2)? typeof window undefined false
I20150907-11:12:18.878(2)? typeof self undefined false
```

**Comment by nate-strauser** [comment]
Would wrapping in a 'Meteor.startup' block do the trick?

**Comment by gilbertwat** [comment]
I have found the problem to be the StateMachine is not exported to the meteor `global` in server, I fixed it by putting two file before and after the statemachine source import.

Basically the library can only use one of the four modules system(node, browser, web worker, amd). Why it work before is that how the StateMachine obj init takes in a `window` parameter and call itself with `this` as argument. This method works great for browser and meteor but not node.js. Then the author changed to [this](https://github.com/jakesgordon/javascript-state-machine/blob/b5e3918837f4c6902ffa33346fcb6ec2e40962e2/state-machine.js#L197), This works for browser and node but not meteor anymore.

Please take a look on the PR #3. Thanks!

**Comment by miri-am** [comment]
I added `api.export('StateMachine');`in the package.js and removed the var in the source code.
